from unittest.mock import call, Mock, patch

from ..db_seeding import seed_db


def test_neo_pixel_seed_db_returns_True():
    with patch("neo_pixel.models.Palette"):
        assert seed_db(Mock())


def test_neo_pixel_seed_db_returns_False():
    with patch("neo_pixel.db_seeding.csv.reader", return_value=[]):
        assert seed_db(Mock()) is False


def test_neo_pixel_seed_db_calls_Palettes():
    db_mock = Mock()
    with patch("neo_pixel.models.Palette") as Palette:
        seed_db(db_mock)
        Palette.assert_has_calls(
            [
                call(
                    name="Outrun",
                    colors=(
                        "#00ffff",
                        "#0394fc",
                        "#0341fc",
                        "#0000ff",
                        "#5500ff",
                        "#7703fc",
                        "#ba03fc",
                        "#de19ff",
                        "#fc03a5",
                    ),
                ),
                call(
                    name="Outrun2",
                    colors=(
                        "#508db8",
                        "#336999",
                        "#78419f",
                        "#a42991",
                        "#cd50ab",
                        "#ec75be",
                        "#f9ac5d",
                        "#fbce88",
                        "#fcecb0",
                    ),
                ),
                call(
                    name="Outrun3",
                    colors=(
                        "#d4475d",
                        "#be687c",
                        "#a172a5",
                        "#d880e2",
                        "#ac90ff",
                        "#6e5aae",
                        "#3264bf",
                        "#7eb4c9",
                        "#79fbf7",
                    ),
                ),
                call(
                    name="Pink-Teals",
                    colors=(
                        "#bb00ff",
                        "#cb00ff",
                        "#dc00ff",
                        "#ee00ff",
                        "#ff00ff",
                        "#00f6fa",
                        "#00ddfa",
                        "#00c8fa",
                        "#00affa",
                    ),
                ),
                call(
                    name="Teal-Pinks",
                    colors=(
                        "#00a7fa",
                        "#00bbfa",
                        "#00d0fa",
                        "#00e9fa",
                        "#00faf6",
                        "#f700ff",
                        "#e500ff",
                        "#d300ff",
                        "#c300ff",
                    ),
                ),
                call(
                    name="PeachGrape",
                    colors=(
                        "#f2a879",
                        "#f2a879",
                        "#f2a88a",
                        "#f2a89b",
                        "#f2a8bd",
                        "#f2a8df",
                        "#f2a8f0",
                        "#f0a8ff",
                        "#f0a8ff",
                    ),
                ),
                call(
                    name="Flowers",
                    colors=(
                        "#f2a8bd",
                        "#fb1256",
                        "#df0c4c",
                        "#fc9a1a",
                        "#f2d645",
                        "#ffff57",
                        "#bcee68",
                        "#b1ffae",
                        "#80e392",
                    ),
                ),
                call(
                    name="Tropical",
                    colors=(
                        "#fe7551",
                        "#f9ae92",
                        "#f9c62a",
                        "#fdd933",
                        "#a9fe51",
                        "#2bf382",
                        "#21a4b9",
                        "#30e7c8",
                        "#34fced",
                    ),
                ),
                call(
                    name="ForestandSky",
                    colors=(
                        "#00ff6c",
                        "#00ff00",
                        "#00ff21",
                        "#00ff44",
                        "#00ffbc",
                        "#00ffd7",
                        "#00bcff",
                        "#008aff",
                        "#0044ff",
                    ),
                ),
                call(
                    name="Christmas",
                    colors=(
                        "#ff1e14",
                        "#f62714",
                        "#ff2128",
                        "#ffd91f",
                        "#23ff14",
                        "#28ff19",
                        "#2dff1e",
                        "#2d2df9",
                        "#fffeed",
                    ),
                ),
                call(
                    name="Pinks",
                    colors=(
                        "#bb00ff",
                        "#c300ff",
                        "#cb00ff",
                        "#d300ff",
                        "#dc00ff",
                        "#e500ff",
                        "#ee00ff",
                        "#f700ff",
                        "#ff00ff",
                    ),
                ),
                call(
                    name="IronSea",
                    colors=(
                        "#00ff46",
                        "#00ff51",
                        "#00ff5c",
                        "#00ff67",
                        "#00ff72",
                        "#00ff7d",
                        "#00ff88",
                        "#00ff93",
                        "#00ff9e",
                    ),
                ),
                call(
                    name="Teals",
                    colors=(
                        "#00a7fa",
                        "#00affa",
                        "#00bbfa",
                        "#00c8fa",
                        "#00d0fa",
                        "#00ddfa",
                        "#00e9fa",
                        "#00f6fa",
                        "#00faf6",
                    ),
                ),
                call(
                    name="Purple",
                    colors=(
                        "#371a94",
                        "#4d22b2",
                        "#5e30eb",
                        "#5500ff",
                        "#5e30eb",
                        "#6744fe",
                        "#7721fc",
                        "#864ffe",
                        "#864ffe",
                    ),
                ),
                call(
                    name="Valentine",
                    colors=(
                        "#ff00aa",
                        "#ff00a0",
                        "#ff0096",
                        "#ff008c",
                        "#ff0082",
                        "#ff0078",
                        "#ff006e",
                        "#ff0064",
                        "#ff005a",
                    ),
                ),
                call(
                    name="Ice",
                    colors=(
                        "#343d5e",
                        "#303f5c",
                        "#446bb4",
                        "#4568bc",
                        "#7a9ae1",
                        "#789ee2",
                        "#bacde4",
                        "#b8cfe7",
                        "#b4d1ef",
                    ),
                ),
                call(
                    name="Fire",
                    colors=(
                        "#9b0100",
                        "#eb1601",
                        "#ff3702",
                        "#ff5803",
                        "#ff7602",
                        "#fe9a01",
                        "#ffce03",
                        "#ffd803",
                        "#ffe807",
                    ),
                ),
            ]
        )
    assert db_mock.add.call_count == 17
