listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
# logging to both stdout and file allows the mqttlogs Make recipe to work
# while still persisting the log output on the host machine
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type all
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
