[pytest]
env =
    DB_HOST=csm-postgres-db-dev
    DB_NAME=testdb
    DB_USER=testuser
    DB_PW=testpw
    MQTT_CLIENT_ID_SUFFIX=pytest
    BACKEND_STREAM_NAME=csm-backend-stream-dev
    WEBSOCKETS_STREAM_NAME=csm-websockets-stream-dev
asyncio_default_fixture_loop_scope = function
