[pytest]
env =
    DB_HOST=csm-postgres-db-dev
    DB_NAME=testdb
    DB_USER=testuser
    DB_PW=testpw
    MQTT_CLIENT_ID_PREFIX=pytest
    BACKEND_STREAM_NAME=BACKEND_STREAM_NAME
    WEBSOCKETS_STREAM_NAME=WEBSOCKETS_STREAM_NAME
asyncio_default_fixture_loop_scope = function
